# Generated by Django 5.0.7 on 2024-08-09 11:10

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPSTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=200, unique=True, verbose_name='Serial Number')),
            ],
            options={
                'db_table': 'gpstracker',
            },
        ),
        migrations.CreateModel(
            name='RFID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid_code', models.CharField(max_length=100, unique=True, verbose_name='RFID Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'db_table': 'rfid',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(max_length=100, verbose_name='Zone Name')),
            ],
            options={
                'db_table': 'zone',
            },
        ),
        migrations.CreateModel(
            name='FleetOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=200, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=200, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email Address')),
                ('contact_number', models.CharField(max_length=10, verbose_name='Contact Number')),
                ('address', models.TextField(max_length=200, verbose_name='Address')),
                ('aadhar_number', models.CharField(max_length=12, unique=True, verbose_name='Aadhar Number')),
                ('pan_number', models.CharField(max_length=10, unique=True, verbose_name='PAN Number')),
                ('resident_proof', models.ImageField(upload_to='fleetowner_uploads/', verbose_name='Resident Proof')),
                ('last_login', models.DateTimeField(auto_now_add=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'fleetowner',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20, unique=True, verbose_name='Registration Number')),
                ('registration_date', models.DateField(verbose_name='Registration Date')),
                ('vehicle_name', models.CharField(max_length=100, verbose_name='Vehicle Name')),
                ('colour', models.CharField(max_length=50, verbose_name='Colour')),
                ('model', models.CharField(max_length=50, verbose_name='Model')),
                ('chassis_number', models.CharField(max_length=100, unique=True, verbose_name='Chassis Number')),
                ('insurance', models.BooleanField(default=1, verbose_name='Insurance')),
                ('puc', models.BooleanField(default=1, verbose_name='PUC')),
                ('seating_capacity', models.CharField(max_length=2, verbose_name='Seating Capacity')),
                ('fuel_type', models.CharField(max_length=100, verbose_name='Fuel Type')),
                ('air_condition', models.BooleanField(default=1, verbose_name='Air Condition')),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL)),
                ('tracker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restapi_app.gpstracker')),
            ],
            options={
                'db_table': 'car',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=200, verbose_name='Driver Name')),
                ('driver_licence_number', models.CharField(max_length=20, verbose_name='Driver Licence Number')),
                ('issue_date', models.DateField(verbose_name='Issue Date')),
                ('valid_till', models.DateField(verbose_name='Valid Till')),
                ('address', models.TextField(verbose_name='Address')),
                ('upload_licence', models.ImageField(upload_to='licence_uploads/', verbose_name='Upload Licence')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi_app.car')),
                ('rfid', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restapi_app.rfid', verbose_name='RFID')),
            ],
            options={
                'db_table': 'driver',
            },
        ),
        migrations.CreateModel(
            name='Tracker_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=30, verbose_name='Zone')),
                ('vendor', models.CharField(max_length=200, verbose_name='Vendor')),
                ('auth_key', models.CharField(max_length=200, verbose_name='Authentication Key')),
                ('latitude', models.FloatField(max_length=10, verbose_name='Latitude')),
                ('longitude', models.FloatField(max_length=10, verbose_name='Longitude')),
                ('speed', models.FloatField(max_length=10, verbose_name='Speed')),
                ('accuracy', models.FloatField(max_length=10, verbose_name='Accuracy')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='Timestamp')),
                ('panic', models.BooleanField(default=0, verbose_name='Panic')),
                ('ignition', models.BooleanField(default=1, verbose_name='Ignition')),
                ('air_condition', models.CharField(max_length=10, verbose_name='Air Condition')),
                ('status', models.CharField(default='01', max_length=2)),
                ('car', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restapi_app.car')),
            ],
            options={
                'db_table': 'tracker_data',
            },
        ),
    ]
